Repository acemod/ACE-Anvil, pull requests merged in 2024-04, with the labels that each got.

#24 Medical - Fix minor typo in documentation
  docs/src/content/docs/components/medical.mdx
Labels: kind/documentation

#27 Carrying - Delay deletion of helper compartment
  addons/carrying/Scripts/Game/ACE_Carrying/Entities/ACE_Carrying_Helper.c
Labels: kind/bug

#25 Add some french strings
  addons/chopping/Language/ACE_Chopping_localization.fr_fr.conf
  addons/chopping/Language/ACE_Chopping_localization.st
  addons/core/Language/ACE_localization.fr_fr.conf
  addons/core/Language/ACE_localization.st
  addons/finger/Language/ACE_Finger_localization.fr_fr.conf
  addons/finger/Language/ACE_Finger_localization.st
  addons/medical/Language/ACE_Medical_localization.cs_cz.conf
  addons/medical/Language/ACE_Medical_localization.de_de.conf
  addons/medical/Language/ACE_Medical_localization.en_us.conf
  addons/medical/Language/ACE_Medical_localization.es_es.conf
  addons/medical/Language/ACE_Medical_localization.fr_fr.conf
  addons/medical/Language/ACE_Medical_localization.it_it.conf
  addons/medical/Language/ACE_Medical_localization.ja_jp.conf
  addons/medical/Language/ACE_Medical_localization.ko_kr.conf
  addons/medical/Language/ACE_Medical_localization.pl_pl.conf
  addons/medical/Language/ACE_Medical_localization.pt_br.conf
  addons/medical/Language/ACE_Medical_localization.ru_ru.conf
  addons/medical/Language/ACE_Medical_localization.st
  addons/medical/Language/ACE_Medical_localization.uk_ua.conf
  addons/medical/Language/ACE_Medical_localization.zh_cn.conf
Labels: kind/translation

#26 Add Czech localization
  addons/carrying/Language/ACE_Carrying_localization.cs_cz.conf
  addons/carrying/Language/ACE_Carrying_localization.st
  addons/chopping/Language/ACE_Chopping_localization.cs_cz.conf
  addons/chopping/Language/ACE_Chopping_localization.st
  addons/core/Language/ACE_localization.cs_cz.conf
  addons/core/Language/ACE_localization.st
  addons/finger/Language/ACE_Finger_localization.cs_cz.conf
  addons/finger/Language/ACE_Finger_localization.st
  addons/medical/Language/ACE_Medical_localization.cs_cz.conf
  addons/medical/Language/ACE_Medical_localization.st
Labels: kind/translation

#29 Add release notes config
  .github/release.yml
Labels: ignore-changelog

#34 Add bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: ignore-changelog

#49 Docs - Add hint that bool has to be provided as int
  docs/src/content/docs/components/medical.mdx
Labels: kind/documentation

#33 Carrying - Clean up helper compartment
  addons/carrying/Prefabs/Helpers/ACE_Carrying_HelperCompartment.et
  addons/carrying/Prefabs/Helpers/ACE_Carrying_HelperCompartment.et.meta
  addons/carrying/Scripts/Game/ACE_Carrying/Entities/ACE_Carrying_HelperCompartment.c
  addons/carrying/Scripts/Game/ACE_Carrying/GameMode/SCR_BaseGameMode.c
  addons/carrying/Scripts/Game/ACE_Carrying/Tools/ACE_Carrying_Tools.c
  addons/carrying/Scripts/Game/ACE_Carrying/UI/HUD/AvailableActions/SCR_AvailableActionsConditionData.c
  addons/carrying/Scripts/Game/ACE_Carrying/UserActions/ACE_Carrying_CarryUserAction.c
  addons/carrying/Scripts/Game/ACE_Carrying/UserActions/SCR_GetInUserAction.c
Labels: kind/cleanup

#42 Core - Increase weight and volume of bananas
  addons/core/Prefabs/Items/Core/ACE_Banana.et
  addons/core/Prefabs/Weapons/Grenades/ACE_FragBanana.et
Labels: kind/enhancement

#44 Carrying - Make carry action unavailable while target ragdolls
  addons/carrying/Scripts/Game/ACE_Carrying/UserActions/ACE_Carrying_CarryUserAction.c
Labels: kind/bug

#32 Medical - Broadcast second chance to all clients
  addons/medical/scripts/Game/ACE_Medical/Character/SCR_CharacterControllerComponent.c
  addons/medical/scripts/Game/ACE_Medical/Components/Damage/SCR_CharacterDamageManagerComponent.c
  addons/medical/scripts/Game/ACE_Medical/HitZone/SCR_CharacterHealthHitZone.c
  addons/medical/scripts/Game/ACE_Medical/Player/SCR_PlayerController.c
Labels: kind/bug

#54 Medical - Revise resilience regeneration rate for second chance
  addons/medical/scripts/Game/ACE_Medical/Components/Damage/SCR_CharacterDamageManagerComponent.c
  addons/medical/scripts/Game/ACE_Medical/Settings/ACE_Medical_SettingsConfig.c
  docs/src/content/docs/components/medical.mdx
Labels: kind/enhancement

#48 Chopping - Replace ActionsManagerComponent on plant with helper
  addons/chopping/Config/ACE/Chopping.conf
  addons/chopping/Config/ACE/Chopping.conf.meta
  addons/chopping/Prefabs/Helpers/ACE_Chopping_BaseHelper.et
  addons/chopping/Prefabs/Helpers/ACE_Chopping_BaseHelper.et.meta
  addons/chopping/Prefabs/Helpers/ACE_Chopping_BushHelper.et
  addons/chopping/Prefabs/Helpers/ACE_Chopping_BushHelper.et.meta
  addons/chopping/Prefabs/Helpers/ACE_Chopping_TreeHelper.et
  addons/chopping/Prefabs/Helpers/ACE_Chopping_TreeHelper.et.meta
  addons/chopping/Prefabs/Vegetation/Core/Bush_Base.et
  addons/chopping/Prefabs/Vegetation/Core/Tree_Base.et
  addons/chopping/scripts/Game/ACE_Chopping/Building/SCR_CampaignBuildingGadgetToolComponent.c
  addons/chopping/scripts/Game/ACE_Chopping/Configs/ACE_Chopping_Config.c
  addons/chopping/scripts/Game/ACE_Chopping/Entities/ACE_Chopping_HelperEntity.c
  addons/chopping/scripts/Game/ACE_Chopping/UserActions/ACE_Chopping_UserAction.c
  addons/core/Assets/Helpers/ACE_InteractionCube.fbx
  addons/core/Assets/Helpers/ACE_InteractionCube.txo
  addons/core/Assets/Helpers/ACE_InteractionCube.xob
  addons/core/Assets/Helpers/ACE_InteractionCube.xob.meta
Labels: kind/enhancement

#56 Carrying - Revert to not broadcast attaching/detaching of helper
  addons/carrying/Scripts/Game/ACE_Carrying/Entities/ACE_Carrying_HelperCompartment.c
Labels: kind/bug

#59 Medical - Revise visibility of bandage user action
  addons/medical/scripts/Game/UserActions/SCR_BandageUserAction.c
Labels: kind/bug
