Repository acemod/ACE-Anvil, pull requests merged in 2024-12, with the labels that each got.

#131 Chopping - Add floating action context
  addons/chopping/Prefabs/Helpers/ACE_Chopping_BaseHelper.et
Labels: kind/enhancement, 1.2.1

#112 Trenches - Fix orientation of built trenches
  addons/trenches/scripts/Game/ACE_Trenches/Building/SCR_CampaignBuildingNetworkComponent.c
Labels: kind/bug

#80 Add ACE Explosives
  AUTHORS
  addons/chopping/Prefabs/Helpers/ACE_Chopping_BaseHelper.et
  addons/chopping/scripts/Game/ACE_Chopping/UserActions/ACE_Chopping_UserAction.c
  addons/core/scripts/Game/ACE_Core/UserActions/ACE_GadgetUserAction.c
  addons/core/scripts/Game/ACE_Core/UserActions/ACE_ShovelUserAction.c
  addons/core/scripts/Game/ACE_Core/UserActions/ACE_WrenchUserAction.c
  addons/explosives/Language/ACEExplosivesLocalization.cs_cz.conf
  addons/explosives/Language/ACEExplosivesLocalization.de_de.conf
  addons/explosives/Language/ACEExplosivesLocalization.en_us.conf
  addons/explosives/Language/ACEExplosivesLocalization.es_es.conf
  addons/explosives/Language/ACEExplosivesLocalization.fr_fr.conf
  addons/explosives/Language/ACEExplosivesLocalization.it_it.conf
  addons/explosives/Language/ACEExplosivesLocalization.ja_jp.conf
  addons/explosives/Language/ACEExplosivesLocalization.ko_kr.conf
  addons/explosives/Language/ACEExplosivesLocalization.pl_pl.conf
  addons/explosives/Language/ACEExplosivesLocalization.pt_br.conf
  addons/explosives/Language/ACEExplosivesLocalization.ru_ru.conf
  addons/explosives/Language/ACEExplosivesLocalization.uk_ua.conf
  addons/explosives/Language/ACEExplosivesLocalization.zh_cn.conf
  addons/explosives/Language/ACE_Explosives_Localization.cs_cz.conf
  addons/explosives/Language/ACE_Explosives_Localization.cs_cz.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.de_de.conf
  addons/explosives/Language/ACE_Explosives_Localization.de_de.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.en_us.conf
  addons/explosives/Language/ACE_Explosives_Localization.en_us.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.es_es.conf
  addons/explosives/Language/ACE_Explosives_Localization.es_es.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.fr_fr.conf
  addons/explosives/Language/ACE_Explosives_Localization.fr_fr.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.it_it.conf
  addons/explosives/Language/ACE_Explosives_Localization.it_it.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.ja_jp.conf
  addons/explosives/Language/ACE_Explosives_Localization.ja_jp.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.ko_kr.conf
  addons/explosives/Language/ACE_Explosives_Localization.ko_kr.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.pl_pl.conf
  addons/explosives/Language/ACE_Explosives_Localization.pl_pl.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.pt_br.conf
  addons/explosives/Language/ACE_Explosives_Localization.pt_br.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.ru_ru.conf
  addons/explosives/Language/ACE_Explosives_Localization.ru_ru.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.st
  addons/explosives/Language/ACE_Explosives_Localization.st.meta
  addons/explosives/Language/ACE_Explosives_Localization.uk_ua.conf
  addons/explosives/Language/ACE_Explosives_Localization.uk_ua.conf.meta
  addons/explosives/Language/ACE_Explosives_Localization.zh_cn.conf
  addons/explosives/Language/ACE_Explosives_Localization.zh_cn.conf.meta
  addons/explosives/Prefabs/Weapons/Core/ExplosiveCharge_base.et
  addons/explosives/Prefabs/Weapons/Core/ExplosiveCharge_base.et.meta
  addons/explosives/Prefabs/Weapons/Core/Mine_base.et
  addons/explosives/Prefabs/Weapons/Core/Mine_base.et.meta
  addons/explosives/addon.gproj
  addons/explosives/license.txt
  addons/explosives/scripts/Game/ACE_Explosives/Demining/UserActions/ACE_Explosives_DisarmUserAction.c
  addons/explosives/thumbnail.png
  docs/src/content/docs/components/explosives.mdx
Labels: kind/feature

#109 Trenches - Use terrain material for dirt covers
  addons/trenches/Common/Materials/ACE_Trenches_MatTerrainObj.emat
  addons/trenches/Common/Materials/ACE_Trenches_MatTerrainObj.emat.meta
  addons/trenches/Prefabs/Compositions/Misc/FreeRoamBuilding/ACE_DirtCover_01_long_v1.et
  addons/trenches/Prefabs/Compositions/Misc/FreeRoamBuilding/ACE_DirtCover_01_short.et
  addons/trenches/PrefabsEditable/Auto/Structures/Military/Fortifications/E_ACE_DirtCover_01_long_v1.et
  addons/trenches/PrefabsEditable/Auto/Structures/Military/Fortifications/E_ACE_DirtCover_01_short.et
  addons/trenches/PrefabsEditable/Auto/Structures/Military/Fortifications/E_ACE_DirtCover_Base.et
Labels: kind/feature

#142 Fix docs for float-based mission header settings
  docs/src/content/docs/components/finger.mdx
  docs/src/content/docs/components/medical.mdx
Labels: kind/documentation

#137 Fixes for Reforger `1.3.0.18`
  addons/carrying/Scripts/Game/ACE_Carrying/UserActions/ACE_Carrying_CarryUserAction.c
  addons/core/scripts/Game/ACE_Core/UserActions/ACE_GadgetUserAction.c
  addons/medical/scripts/Game/ACE_Medical/Components/Damage/SCR_CharacterDamageManagerComponent.c
  addons/medical/scripts/Game/ACE_Medical/Components/Gadgets/ACE_Medical_ConsumableEpinephrine.c
  addons/medical/scripts/Game/ACE_Medical/Components/Gadgets/ACE_Medical_ConsumableMorphine.c
Labels: kind/bug, 1.3.0.x

#136 All in One - Add ACE Explosives
  addons/all_in_one/addon.gproj
Labels: ignore-changelog
