Repository acemod/ACE-Anvil, pull requests merged in 2024-06, with the labels that each got.

#70 Medical - Fix preview orientation of epinephrine injector
  addons/medical/Prefabs/Items/Medicine/EpinephrineInjection/ACE_Medical_EpinephrineInjection.et
Labels: kind/bug, 1.2

#76 Trenches - Fix for `1.2.0.66`
  addons/trenches/Prefabs/Items/Equipment/Accessories/ETool_ALICE/ETool_ALICE_FreeRoamBuilding_Gadget.et
  addons/trenches/Prefabs/Items/Equipment/Accessories/ETool_ALICE/ETool_ALICE_FreeRoamBuilding_Gadget.et.meta
  addons/trenches/Prefabs/Items/Equipment/Accessories/ETool_MPL50/ETool_MPL50_FreeRoamBuilding_Gadget.et
  addons/trenches/Prefabs/Items/Equipment/Accessories/ETool_MPL50/ETool_MPL50_FreeRoamBuilding_Gadget.et.meta
  addons/trenches/scripts/Game/ACE_Trenches/Building/SCR_CampaignBuildingGadgetToolComponent.c
Labels: kind/bug, 1.2

#51 Integrate SESOF MagRepack
  AUTHORS
  addons/magrepack/addon.gproj
  addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
  addons/magrepack/scripts/Game/ACE_MagRepack/UI/Inventory/SCR_InventoryMenuUI.c
  addons/magrepack/thumbnail.png
  docs/src/content/docs/components/magrepack.mdx
Labels: kind/feature, 1.2

#77 Medical - Update morphine prefab
  addons/medical/Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et
Labels: kind/bug, 1.2

#79 Magrepack - Fix documentation
  addons/magrepack/license.txt
  docs/src/content/docs/components/magrepack.mdx
Labels: kind/documentation

#82 MagRepack - Fix `null` in target storage
  addons/magrepack/scripts/Game/ACE_MagRepack/UI/Inventory/SCR_InventoryMenuUI.c
Labels: kind/bug
