Repository acemod/ACE-Anvil, pull requests merged in 2025-04, with the labels that each got.

#177 All in One - Update mod list and docs
  addons/all_in_one/addon.gproj
  docs/src/content/docs/components/captives.mdx
  docs/src/content/docs/components/carrying.mdx
  docs/src/content/docs/components/radio.mdx
Labels: ignore-changelog

#180 Captives - Handle null exceptions
  addons/core/scripts/Game/ACE_Core/Components/ACE_CarriableEntityComponent.c
  addons/core/scripts/Game/ACE_Core/UserActions/ACE_BaseGadgetUserAction.c
Labels: kind/bug, ignore-changelog

#178 Core - Remove duplicate code
  addons/core/scripts/Game/ACE_Core/Components/ACE_CarriableEntityComponent.c
  addons/core/scripts/Game/ACE_Core/Player/SCR_PlayerController.c
  addons/core/scripts/Game/ACE_Core/UserActions/ACE_BaseGadgetUserAction.c
Labels: kind/bug, ignore-changelog

#192 Core - Gadget use ended handler did not get removed
  addons/core/scripts/Game/ACE_Core/UserActions/ACE_BaseGadgetUserAction.c
Labels: kind/bug

#187 Tactical Ladder - Add obstruction check for top exit
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.cs_cz.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.de_de.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.en_us.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.es_es.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.fr_fr.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.it_it.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.ja_jp.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.ko_kr.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.pl_pl.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.pt_br.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.ru_ru.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.st
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.uk_ua.conf
  addons/tactical_ladder/Language/ACE_TacticalLadder_localization.zh_cn.conf
  addons/tactical_ladder/scripts/Game/ACE_TacticalLadder/Entities/ACE_TacticalLadderEntity.c
  addons/tactical_ladder/scripts/Game/ACE_TacticalLadder/UserActions/ACE_TacticalLadder_LadderUserAction.c
Labels: kind/enhancement

#185 Tactical Periscope - Fix periscope was visible when gear has a binocular slot.
  addons/tactical_periscope/Prefabs/Items/Equipment/Periscope/ACE_TacticalPeriscope.et
  addons/tactical_periscope/scripts/Game/ACE_TacticalPeriscope/Components/Gadgets/ACE_TacticalPeriscope_GadgetComponent.c
Labels: kind/bug

#182 Captives - Prevent self-interaction of captives
  addons/captives/scripts/Game/ACE_Captives/UserActions/ACE_Captives_EscortCaptiveUserAction.c
  addons/captives/scripts/Game/ACE_Captives/UserActions/ACE_Captives_ReleaseCaptiveUserAction.c
Labels: kind/bug

#181 Tactical Periscope - Fix PIP material
  addons/tactical_periscope/Assets/Items/Periscope/ACE_TacticalPeriscope.xob
  addons/tactical_periscope/Assets/Items/Periscope/ACE_TacticalPeriscope.xob.meta
Labels: kind/bug

#189 Tactical Ladder - Prevent stacking of ladders
  addons/core/scripts/Game/ACE_Core/Components/SCR_ItemPlacementComponent.c
  addons/core/scripts/Game/ACE_Core/Components/SCR_PlaceableItemComponent.c
  addons/tactical_ladder/Prefabs/Items/Equipment/TacticalLadder/ACE_TacticalLadder.et
Labels: kind/enhancement

#201 Tactical Ladder - Fix display name when replacing ladder
  addons/tactical_ladder/Prefabs/Items/Equipment/TacticalLadder/ACE_TacticalLadder.et
Labels: kind/bug

#204 Tactical Ladder - Fix placement when dropped from inventory
  addons/tactical_ladder/scripts/Game/ACE_TacticalLadder/Entities/ACE_TacticalLadderEntity.c
Labels: kind/bug

#207 Captives - Fix last instigator getting punished when captive respawns
  addons/captives/scripts/Game/ACE_Captives/Systems/ACE_Captives_CaptiveSystem.c
Labels: kind/bug

#209 Docs - Update npm packages
  docs/package.json
  docs/pnpm-lock.yaml
Labels: ignore-changelog, area/tools
